### ISSUE TITLE
Non-aligned portals

### ISSUE THREAD

**Issue by KamenB** [IbakonFerba/QuantumVR#1]
Hey!

I absolutely love your thesis, after searching for portals in VR in the past week, I can confidently say it is miles ahead of anything else freely available online. I have been trying to get the rendering for the portal working, when the in-portal and the out-portal are at a different (e.g. 90 degree) angle. The idea is to have the 3-room square seen in this video: [https://youtu.be/kEB11PQ9Eo8?t=42](https://youtu.be/kEB11PQ9Eo8?t=42)
I would appreciate it a lot if you can tell me whether the underlying methods you use (stencil buffering for recursive portal rendering) work for that set up. Or is your approach constrained to only situations where the in and out portal face 180 degrees from each other?

Many thanks in advance!

**Comment by IbakonFerba** [comment]
Hey,
Unfortunately that is not possible with the approach I'm using here. You see, this tool was specifically built to compress space while feeling as realistic as possible and not to be a complete non-Euclidean engine.
With the stencil buffer approach you cannot "bend" the view. The objects are rendered as they would be in a normal scene, only that they can be on different spatial layers (imagine them like parallel Universes).
I hope this makes it clear to you, I always find it a little hard to talk about what exactly is going on here ;)

**Comment by KamenB** [comment]
That makes perfect sense, thank you and thanks for the quick response! I wish you a smooth journey onwards from your Bachelors! :)
